project:
  type: book
  output-dir: docs

book:
  title: "Voyage en Ednom : le Livret de Règles"
  subtitle: "Version 1.1"
  author: "Rémi Bodinier"
  date: today

  chapters:
    - index.qmd

    - part: "Aide de jeu"
      chapters:
      - aide_jeu.qmd
      - j02caretcomp.qmd
      - j03talent.qmd
      - j04magie.qmd
      - j05equipement.qmd
      - j06artisanat.qmd
      - j07archetype.qmd
      - j08jet_combat.qmd

    - part: "Le Monde d'Ednom"
      chapters:
        - j01Ednom.qmd
        - j01nom.qmd
        - j02nature.qmd


#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: default
