project:
  type: book
  output-dir: docs

book:
  title: "Voyage en Ednom : le Livret de Règles"
  subtitle : "Version 1.1"
  author: "Rémi Bodinier"
  date: today
  chapters:
    - index.qmd
    - part : aide_jeu.qmd
      chapters :
      - j01nom.qmd
      - j02caretcomp.qmd
      - j03talent.qmd
      - j04magie.qmd
      - j05equipement.qmd
      - j06archetype.qmd
      - j07jet_combat.qmd
    - part : ednom.qmd
      chapters :
      - j04Ednom.qmd
      - j05nature.qmd


#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx : default



