project:
  type: book
  output-dir: docs

book:
  title: "Voyage en Ednom : le livret de règles"
  author: "Rémi Bodinier"
  date: today
  chapters:
    - index.qmd
    - j01Ednom.qmd
    - j02nom.qmd
    - j03caretcomp.qmd
    - j04talent.qmd
    - j05magie.qmd
    - j06equipement.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



