project:
  type: book
  output-dir: docs

book:
  title: "Voyage en Ednom : le livret de règles"
  author: "Rémi Bodinier"
  date: today
  chapters:
    - index.qmd
    - j01Ednom.qmd
    - j02nom.qmd
    - j03caretcomp.qmd
    - j04talent.qmd
    - j05equipement.qmd 
    - j06magie.qmd
    - j07combat.qmd
    - j08archetype.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



