project:
  type: book
  output-dir: docs

book:
  title: "Voyage en Ednom : le Livret de Règles"
  subtitle: "Version 1.1"
  author: "Rémi Bodinier"
  date: today

  chapters:
    - index.qmd

    - part: "Règles du jeu"
      chapters: 
      - aide_jeu.qmd
      - j08jet_combat.qmd

    - part: "Caractéristiques et compétence"
      chapters:  
      - j02caretcomp.qmd
      - artisanat.qmd
      - arts.qmd
      - athletisme.qmd
      - culture_generale.qmd
      - deguisement.qmd
      - discretion.qmd
      - estimation.qmd
      - habilete.qmd
      - influence.qmd
      - investigation.qmd
      - perception.qmd
      - precision.qmd
      - puissance.qmd
      - science.qmd
      - utilisation_ether.qmd

    - part: "Magie"
      chapters:
      - j04magie.qmd

    - part: "Equipement et Artisanat"
      chapters: 
      - j05equipement.qmd
      - j06artisanat.qmd

    - part: "Personnages précréés"
      chapters : 
      - j07archetype.qmd
      

    - part: "Le Monde d'Ednom"
      chapters:
        - j01Ednom.qmd
        - j01nom.qmd
        - j02nature.qmd


#bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: default
