# Préface {.unnumbered}

Bienvenu, chers voyageurs, dans le monde d'Ednom. 

Ednom est un monde médiéval fantastique dans lequel vous allez pouvoir évoluer en tant qu'aventuriers. 

Ce mot a un sens tout particulier dans ce monde. Les acenturiers sont des personnes, de toutes races et de toutes origines, ayant choisi comme profession de ce mettre au service des autres. Que ce soit pour aider quelqu'un à s'occuper de sa demeure ou vaincre une menace pesant sur le monde, les tâches de l'aventurier sont aussi variées qu'il y a de commanditaires. 

Ainsi, au fil des ans, les aventuriers se sont organisés. Une Guilde des Aventuriers s'est créée, établissant des comptoirs dans toutes les villes de tous les pays. Ces guildes servent d'intermédiaire entre un commanditaire et un aventurier. Elle récolte les demandes de la région qu'elle gère, et redistribue aux aventuriers qu'elle administre. Un client vient avec une demande, la guilde fixe la récompense selon la difficulté de la tâche et les moyens du demandeur puis, une fois la tâche accompli, paye le ou les aventuriers et se charge de récupérer la récompense auprès du client. 
Comme il n'est pas rare que les aventuriers exercent dans une région précise, les comptoirs de la Guilde connaissent bien les capacités et spécificités des aventuriers qui viennent chercher de travail auprès d'elle. Afin d'assigner plus rapidement une tâche à une personne ou à un groupe, la Guilde est également chargée de donner un rang aux aventuriers. Il existe neuf rangs qui sont communs à toutes les guildes au monde. Voici ces neuf rangs : 
1. Recrue
2. Novice
3. Apprenti
4. Acolyte
5. Adepte 
6. Maître
7. Champion
8. Parangon
9. Héros
Cette classification permet surtout une sécurité pour les aventuriers. Selon la difficulté de la tâche demandée, l'offre de quête ne sera disponible qu'à partir d'un certain rang. De plus, un client peut toutà fait demander que les aventuriers s'occupant de la tâche pour laquelle il fait une demande aient un certain classement.  

Maintenant que vous savez comment vous débrouillez en tant qu'aventurier, il vous faut construire, grâce aux pages à venir, l'avatar qui vous conviendra le mieux pour parcourir le monde extraordinaire d'Ednom.