# Le monde d'Ednom

## Généralités

Le monde d'Ednom est un monde médiéval fantastique dans lequel un grand nombre de race cohabitent.

## Les aventuriers

Ce mot a un sens tout particulier dans ce monde. Les aventuriers sont des personnes, de toutes races et de toutes origines, ayant choisi comme profession de ce mettre au service des autres. Que ce soit pour aider quelqu'un à s'occuper de sa demeure ou vaincre une menace pesant sur le monde, les tâches de l'aventurier sont aussi variées qu'il y a de commanditaires. 

Ainsi, au fil des ans, les aventuriers se sont organisés. Une Guilde des Aventuriers s'est créée, établissant des comptoirs dans toutes les villes de tous les pays. Ces guildes servent d'intermédiaire entre un commanditaire et un aventurier. Elle récolte les demandes de la région qu'elle gère, et redistribue aux aventuriers qu'elle administre. Un client vient avec une demande, la guilde fixe la récompense selon la difficulté de la tâche et les moyens du demandeur puis, une fois la tâche accompli, paye le ou les aventuriers et se charge de récupérer la récompense auprès du client. 

Comme il n'est pas rare que les aventuriers exercent dans une région précise, les comptoirs de la Guilde connaissent bien les capacités et spécificités des aventuriers qui viennent chercher de travail auprès d'elle. Afin d'assigner plus rapidement une tâche à une personne ou à un groupe, la Guilde est également chargée de donner un rang aux aventuriers. Il existe neuf rangs qui sont communs à toutes les guildes au monde. Voici ces neuf rangs : 

1. Recrue
2. Novice
3. Apprenti
4. Acolyte
5. Adepte 
6. Maître
7. Champion
8. Parangon
9. Héros

Cette classification permet surtout une sécurité pour les aventuriers. Selon la difficulté de la tâche demandée, l'offre de quête ne sera disponible qu'à partir d'un certain rang. De plus, un client peut toutà fait demander que les aventuriers s'occupant de la tâche pour laquelle il fait une demande aient un certain classement.  

## Nidob

Nidob est un royaume divisé en cinq grande régions :

- Cardia est le centre de ce royaume, autant géographique que politique. C'est dans cette région que se trouve la capitale du Royaume et la famille royale. C'est la région la plus peuplée. 
- Eguzkia, au sud, est composée majoritairement d'un immense désert qui commence dès le littoral sud de la région et couvre 80% du territoire. Ce désert devient une savane puis des collines verdoyantes au climat méditerranéen plus on mont vers le nord. Eguzkia a une petite frontière avec la région à l'ouest, Douar, composée d'une jungle, et une autre petite frontière avec la région à l'est, Nebo, composée d'un relief escarpé composé de pic rocheux et de canyons. Sa frontière principale est avec Cardia et elle se manifeste sous la forme du plus long fleuve de Nidob. Malgré l'énorme désert, Eguzkia est la région la plus riche de Nidob, grâce aux mines de métaux précieux dans le désert, et la culture de produit de luxe quand le climat devient plus indulgent. Le fleuve permet un transport rapide des marchandises vers Cardia, et a donc encore plus favorisé la richesse de cette région. Cependant, l'accumulation de ces richesses a aussi engendré une augmentation de la criminalité dans cette région. De ce fait, les gens du sud sont plutôt rusés, discrets, dextres et ambitieux. Ils peuvent cependant se montrer sournois et méfiants. C'est d'ailleurs la deuxième région la plus peuplée de Nidob.
- Douar, à l'ouest, est composée de plaines alluviales propices à la création de marais le long des multiples rivières traversant la région. Le reste de cette région est majoritairement composé de forêts denses et impénétrables. Tous les types de forêts sont présents à Douar : des jungles humides au sud de la région, au froides forêts de conifères au nord en passant pas des forêts de feuillus majestueux. La forêt est tellement présente que ce sont des forêts qui forment les frontières avec les autres régions. Une jungle au sud représente la frontière avec Eguzkia, une taïga représente la frontière avec Mane, la région au nord de Nidob, et la forêt de Krouadnez représente la frontière avec Cardia. Les principales ressources de la région repose dans la chasse, l'élevage et la sylviculture. En effet les crues dans les nombreuses zones humides empêchent bien souvent une culture pérenne mais de nombreuses espèces en ont fait leur lieu de vie, amélioré par la qualité des ressources disponibles grâce à l'eau et aux limons que déposent les crues. Ainsi, le commerce de fourrure ou viande de luxe est très présent, et le bétail peut être en bonne santé. De plus les nombreuses forêts ont permis à la région d'utiliser le bois sous toutes ses formes : que ce soit pour la construction navale (de nombreuses ville étant sur la côte sont des chantiers navaux) ou bien pour la construction de matériel ou de meubles. Les gens de Douar sont très proches de la nature qui leur fournit leur ressource et avec qui ils ont appris à vivre. Ils sont également de très bon sportifs, leur corps étant affutés par la chasse et le déplacement dans cette nature sauvage. Enfin, ils ont souvent de bonne capacité de perception, que ce soit physique ou bien concernant la mentalité des autres. Cependant, les douariens peuvent paraître austère ou renfermé sur eux-mêmes, n'accordant pas leur confiance facilement. En terme de population, Douar se place à la quatrième place des régions de Nidob.
- Mane, la région du nord, est une région ou le froid est omniprésent. Ce froid est tout d'abord représenté par une taïga qui recouvre l'entiereté de sa frontière sud, et ainsi la frontière avec Douar au sud-ouet, Nebo au sud-est et Cardia sur tout le reste. Le froid est aussi représenté par de chaînes de montagnes, immenses et glaciales, découpant la région à plusieurs endroits. A mesure que l'on monte vers le nord, les arbres se raréfient pour laisser place à une toundra gelées puis la neige et la glace recouvre la terre pour ne laisse qu'un immense manteau blanc s'enfonçant à l'extrême nord dans un océan ponctué d'iceberg. La principale caractéristique de cette région est qu'en son sol réside d'énormes poches d'Ether, la magie dans le monde d'Ednom. Ainsi, les mages du Royaume de Nidob résident quasiment tous dans cette région. Outre les mages, on peut dire que Mane est la région des érudits et des artistes. Les gens s'étant enfermé à cause du froid ont alors augmenté leur capacités intelectuelles plutôt que physiques. On y trouve donc un grand nombre d'ingénieurs et d'inventeurs de génie, des scientifiques en tout genre et des écoles de magies. On retrouve également des mines de combustibles en quantité dans cette réion, permettant d'alimenter les ateliers de nombreux artisans comme des joailliers, des forgerons, des tailleurs, qui font venir des autres régions les ressources nécessaires à leur art. Enfin des écoles de danse, de chant, de peinture et de sculpture ont emergés dans toutes les villes de Mane, permettant au peuple de se divertir dans cette région difficile. Malgré tout cela Mane est la région la moins peuplée de NIdob. Les gens du nord sont donc souvent cultivés, diplomates et ont une volonté inébranlable due à la dureté du milieu. Mais certains se montrent alors pédants et hautains, et la plupart ne présente pas des capacités physiques hors du commun.
- Enfin Nebo se trouve à l'Est de Nidob. Nebo se caractérise surtout par son relief important. En effet, une large chaîne de montagne vient coupé la région en deux, du nord-ouest au sud-est. Cette chaîne présente nombre de pics enneigés, de faille, de ravins et de passages escarpés, mais elle présente aussi de nombreux plateaux montagnards où le climat est doux. De part et d'autres de cette chaîne, le relief s'adoucit pour laisser place à des collines. De nombreuses forêts poussent au pied de cette chaîne montagneuse alors que les plateaux montagnards sont plus clairsemés, permettant de cultiver des champs bien que le sol soit difficile à travailler. La présence de cette chaîne de montagne est également synonyme d'importante ressource en minéraux nécessaires à la production d'outils, d'armes, d'amures. Tous ces facteurs ont fait que la région de Nebo est devenu la principale force militaire de Nidob. Les cultures des plateaux servent à nourrir les soldats alors que les mines et les forêts leur fournissent leur équipement. Les différences de reliefs et d'habitats sont d'autant de possibilité d'entraînements (renforcement physique, connaissance de divers terrain, dressage et monte, ...) pour les nouvelles recrues. Les arbres fournissent également du bois d'une part aux ports de Nebo pour la construction de navire de guerre mais également dans des ateliers pour la confection de machine de siège. Tous ces éléments ont forcés les gens à se rapprocher et les villages à s'agrandir permettant partout dans cette région l'établissement d'école militaire où l'entraînement physique s'accompagnent également d'une éducation aux stratégies militaires. On trouve également de nombreux médecins et hôpital dans cette région, les blessures étant inhérente à la guerre. Outre les milieux qui composent cette région, c'est sans doute également car c'est la région la plus proche de Eripme qui a fait que l'activité tourne autour du monde militaire. Ainsi les gens de Nebo sont souvent droit et ont un grand sens de l'honneur et du devoir, se sont également des bons vivants, habitués à vivre en communauté. Cependant ils peuvent facilement devenir brutaux ou orgeuilleux, et être parfois rustres ou grossiers. C'est la troisième région la plus peuplée de Nidob.