# Choisir son nom

## Origine des noms (lieux et personnages)

Si vous choisissez de venir de Mane, vos prénom et nom doivent s'inspirer du nordique et scandinave.
Si vous choisissez de venir de Nebo, vos prénom et nom doivent s'inspirer du slave.
Si vous choisissez de venir de Eguzkia, vos prénom et nom doivent s'inspirer du basque.
Si vous choisissez de venir de Douar, vos prénom et nom doivent s'inspirer du breton et du celte.
Si vous choisissez de venir de Cardia, vos prénom et nom doivent s'inspirer du latin et du vieux français.

## Cardia

### Liste des villes principales

### Liste des prénoms et noms communs 

#### Les prénoms masculins

#### Les prénoms féminins

#### Les noms de famille

## Eguzkia

### Liste des villes principales

Capitale de Eguzkia :  Hondazuria. 

Ekialdea est une ville au nord-est de la région, à quelques kilomètres de la frontière avec la région de Neb.Cette ville est fortement fortifiée du fait des tensions avec la région voisine. 

### Liste des prénoms et noms communs 

#### Les prénoms masculins

Les prénoms masculins les plus communs dans cette région sont : Bixente, Iban, Eneko, Andoni, Aitor, Patxi, Eder, Peio, Imanol, Pnatxoa, Adei, Gaïzka, Bizen, Gilen.

#### Les prénoms féminins

Les prénoms féminins les plus communs dans cette région sont : Elaia, Lorea, Artéa, Maïka, Elaura, Nahia, Milia, Arima, Btixa, Maïalen, Enea, Ainhoa, Idoia, Maiana, Ekaitza, Oihana, Alodia.

#### Les noms de famille

## Douar

### Liste des villes principales

### Liste des prénoms et noms communs 

#### Les prénoms masculins

Les prénoms masculins les plus communs dans cette région sont : Tristan, Gwendal, Malo, ewen, Morvan, Meriadeg, Loig, Sterenn, Gwenvaël, Yann, Louan, Gaël, Ewan.

#### Les prénoms féminins

Les prénoms féminins les plus communs dans cette région sont : Aesa, Azyliz, Katell, Soizig, Maïwenn, Lena, Kael, Louanne, Gaëlle, Rozen, Armel.

#### Les noms de famille

## Mane

### Liste des villes principales

### Liste des prénoms et noms communs 

#### Les prénoms masculins

Les prénoms masculins les plus communs dans cette région sont : Edwig, Fursy, Hans, Adalbert, Adlaric, Attale, Aloyse, Ernst, Hendrick, Jasper, Lorenz, Othon, Petrus, Renald, Whilhem, Walter, Yerri.

#### Les prénoms féminins

Les prénoms féminins les plus communs dans cette région sont : Edwige, Elsa, Faustine, Fursy, Trudy, Gretel, Hildegarde, Ilda, Iseline, Odehilde, Ruth.

#### Les noms de famille

## Nebo

### Liste des villes principales

### Liste des prénoms et noms communs 

#### Les prénoms masculins

#### Les prénoms féminins

#### Les noms de famille