# La Magie

La magie correspond à l'utilisation d'une matière qu'on appelle Ether. Cette matière peut se trouver à l'état solide, liquide ou gazeux. Naturellement elle est présente dans l'air qui nous entoure ou bien dans des poches sous terre. Cette matière à comme propriété de pouvoir changer de nature et de devenir une nouvelle matière ou bien une nouvelle propriété.  
Les mages, quelle que soit leur origine, ont en fait appris à orienter le changement de matière de l'Ether, pour obtenir des effets voulus. 

## La magie chez les humains.

Sur Ednom les humains utilisent la magie élémentaire créatrice. Ils utilisent l'Ether présent autour d'eux et le transforment en la matière de leur choix. 

### Les sorts connus de la magie humaine

#### Sorts mineurs

Voici la liste des sorts mineurs disponibles à ceux qui ont pris le talent *Initié à la magie* :

- **Appel de la source** : le lanceur pose sa main au sol et change localement la nature du sol afin que l'eau présente remonte en surface. Ne fonctionne que si le sol contient de l'eau naturellement. 
- **Brise** : un vent entoure le lanceur, augmentant la difficulté de le toucher de 5% par des attaques de souffle ou de gaz. 
- **Bruine** : Une légère averse vient tremper la cible. Tout feu égal ou plus petit qu'un feu de camp s'éteint.
- **Etincelles** : Met automatiquement feu à un objet inflammable. Fonctionne comme un silex en plus rapide et quelles que soient les conditions météorologiques
- **Façonnage de la terre** : creuse un trou de 1 mètre de côté ou crée un bloc de terre de 1 mètre de côté.
- **Follets** : des petits flammèches se crééent à quelques mètres devant le mage, produisant de la lumière mais très peu de chaleur.
- **Limon fertile** : le lanceur crée une faible quantité de boue riche en nutriments. Une plante au contact de cette boue éclot et produit son fruit. 
- **Main de vent** : un souffle de vent vient soulever un objet aussi ou moins lourd qu'une choppe pleine (2kg). 
- **Main glacée** : une couche de givre entoure la main du lanceur, permettant de geler tout ce qu'il touche. Les mécanismes d'un objet se paralyse et tout être vivant de la taille ou plus petit qu'une fleur meure d'un contact prolongé.
- **Petits objets de pierre** : crée n'importe quel objet de la taille ou plus petit qu'un marteau, en pierre.

#### Ecole de magie

Si vous avez choisi le talent *Etudiant d'une école de magie*, vous allez pouvoir choisir une des quatres grandes écoles de la magie, chacune basée sur un des quates éléments primaires. Une fois votre école choisie, vous pourrez choisir trois sorts parmi ceux proposés.

##### Ecole du feu

- **Trait de feu** : un trait de feu vient brûler votre adversaire lui causant des dégâts.
- **Balsamine** : trois flammèches sortent de vos main infligeant chacune un tiers des dégâts que vous pouvez occasionner.
- **Cautérisation** : une flamme douce et chaude vient envelopper la blessure que vous voulez guérir afin de rendre des points de vie. Ne fonctionne que pour soigner des dégâts tranchants.
- **Barrière de feu** : une barrière de feu de 2 mètres de largeur se dresse devant le lanceur du sort, qui protège des dégâts magiques 
- **Main brûlantes** : tout ce que le lanceru touche brûle ou fond, tout ce qui est en contact avec le matériau en train de brûler reçoit X dégâts.
- **Boule de feu** : lance une boule de feu infligeant X points de dégâts.
- **Mur de feu** : dresse un mur de feu infranchissable.

##### Ecole de l'eau 

- **Jet d'eau** : un jet d'eau à haute pression heurte la cible du sort, lui infligeant des dégâts perforants.
- **Disques de glace** : trois disques de glace infligeant chacun X dégâts sont envoyés vers les cibles du choix du lanceur. 
- **Eau de vie** : une eau pure vient envelopper la blessure que vous voulez guérir afin de rendre des points de vie. Ne fonctionne que pour des dégâts liés à des brulures ou à des poisons.
- **Prison d'eau** : le lanceur enferme une cible dans une bulle d'eau. La bulle ne peut être détruite tant que le lanceur reste concentré sur le sort.
- **Tsunami** : sort de zone qui emporte toutes les cibles devant le lanceur. Un jet d'athlétisme avec un malus de X permet de rester en place.
- **Mur de glace** : crée une barrière de glace de 2 mètres de large devant le lanceur, arrêtant tous les dégâts pendant X tours. 
- **Tempête de grêle** : invoque de la grêle infligeant X dégâts dans une zone.
- **Geyser** : crée un geyser en dessous d'une cible qui subit X dégâts et est envoyée à X mètres de haut.
- **Armure de glace** :  crée une armure de glace à une cible, retirant X dégâts 

##### Ecole de l'air

- **Souffle revigorant** : une souffle léger court sur la blessure que vous voulez guérir afin de rendre des points de vie. Ne fonctionne que pour des dégâts contondants. 
- **Lame d'air** : une lame d'air vient trancher la cible du sort, lui infligeant des dégâts tranchants.
- **Onde de choc** : un impact de vet vient bousculer la cible, lui ingfligeant des dégâts contondant et la faisant tomber à terre.
- **Bouclier d'air** : un disque se crée devant le lanceur, qui repousse les attaques.  
- **Lévitation** : crée un courant ascendant sous une cible ce qui permet de ralentir une chute ou bien de l'envoyer dans les airs. 
- **Brume** : entoure le lanceur de brume ce qui donne aux personnes le ciblant un malus de X pour le toucher.
- **Bourrasque** : crée une vague de vent fort qui met au sol tous les adversaires. 
- **Mur de vent** : crée une barrière de vent emportant armes, magie et gaz.


##### Ecole de la terre

- **Cataplasme** : une boue à la capacité curative vient remplir la blessure que vous voulez guérir afin de rendre des points de vie. Ne fonctionne que pour des dégâts perforants.
- **Mare de chaux** : une mare de chaux s'étale au sol et se solidifie aux pieds des cibles, les empêchant de bouger. 
- **Catapulte** : un bloc de pierre vient se fracasser contre la cible, lui infligeant des dégâts contondants.
- **Barrière de terre** : une barrière de terre se dresse devant le lanceur, afin d'encaisser des dégâts. 
- **Disques de pierre** : trois disques de pierre sortent de vos mains, infligeant chacun le tiers des dégâts que vous pouvez occasionner.
- **Jet de sable** : un jet de sable vient infliger un cinquième des dégâts et aveugle la cible pendant un certain nombre de tour.
- **Météores** : une pluie de pierre jaillit de vos mains, infligeant la moitié des dégâts que vous pouvez occasionner sur une case et celles à proximité.
- **Poings de pierre** : une couche de pierre vient recouvrir les mains de la cible, ce qui augmente ses dégâts de X points.
- **Armure de roche** : recouvre la cible d'une fine couche de roche qui augmente sa résistance aux dégâts de X points.
 
 ## Magie des autres races

 Les autres races que les humains ont aussi leur propre méthode de faire de la magie. 

 ### Les Elfes

 Les Elfes utilisent l'Ether directement comme énergie pour leur magie. Ils sont ainsi capables de lancer des rayons d'Ether, ils peuvent faire léviter des objets ou des choses vivantes, ils peuvent se rendre invisibe, ...

 ### Les Nains

 Les Nains ont découvert la magie avec le langage des runes. C'est un langage très ancien, aujourd'hui quasiment perdu sauf par le peuple nain. Ce langage permet de donner des ordres à l'Ether pour que celui-ci change. Les nains peuvent donc faire brûler, faire exploser soigner, ...

 ### Le Petit Peuple

 Le Petit Peuple affecte la réalité. Les mages du petit peuple jette des illusions et s'ils sont assez convaincants, les illusions peuvent même devenir réalité.

 ### Les Therianthropes

 Les Therianthropes font des prières à leurs dieux pour que ceux-ci influent sur le cours des choses.   

## Enchantement

Il peut arriver que des objets soit enchantés. En particulier les instruments de musique sont une bonne manière de faire de la magie. 

### Notes magiques

Si vous avez choisi l'instrument enchanté, vous pouvez choisir 3 partition parmi les suivantes :

- **Partition de sommeil** : la cible tombe dans un état de somnolence pendant X tours.