# Les Talents

Bien que vos compétences donne une première vision des actions dans lesquelles vous allez exceller et celles qui vous donneront du fil à retordre, les talents sont un autre aspect de votre personnage lui apportant de la nuance. Vous allez pouvoir en choisir deux en tout et pour tout, à la création de votre personnage. 

## Talents de Compétences

### Talents d'Artisanat

- 

### Talents d'Arts

- 

### Talents d'Athlétisme

- **Attaquant en finesse** : le personnage utilise sa valeur d'*Athlétisme* plutôt que celle de *Combat au corps à corps* pour attaquer avec des armes ne possédant pas la particularité *Distance*. 

### Talents de Combat à distance

- **Maître des [armes]** : votre personnage sait très bien utiliser un type d'armes parmi ceux possédant la particularité *Distance*. Il augmente la valeur de *Combat à distance* de 10% quand il utilise une arme de ce type. 

### Talents de Combat au corps à corps

- **Maître des [armes]** : votre personnage sait très bien utiliser un type d'armes parmi ceux ne possédant pas les particularités *Distance* ni *Lancer*. Il augmente la valeur de *Combat au corps à corps* de 10% quand il utilise une arme de ce type. 

### Talents de Culture générale

- 

### Talents de Dégguisement

-

### Talents de Discrétion

-

### Talents d'Estimation

-

### Talents d'Habilté

-

### Talents d'Influence

-

### Talents d'Investigation

-

### Talents de Perception

-

### Talents de Science

-

### Talents d'Utilisation de l'Ether

- **Initié à la magie** (nécessite 55% en *Utilisation de l'Ether*) : le personnage a suivi un cursus lui permettant d'utiliser des sorts mineurs. Il peut choisir trois sorts mineurs dans la liste présente dans la partie sur la magie.
- **Etudiant d'une école de magie** (nécessite le talent *Initié à la magie*): le personnage a étudié une des quatre grandes écoles de magie et peut lancer trois sorts parmi la liste proposé dans l'école à laquelle il appartient. 

## Talents de familier

- **Piqué** : l'animal pique sur sa cible (jet d'*Athlétisme*) pour le griffer et remonte immédiatement en l'air. Le piqué donne un bonus de 15 au dégâts.
- **Limier** : l'animal bénéficie d'un bonus de 10% quand il fait des jets d'*Investigation* pour suivre une piste olfactive, auditive ou visuelle. 
- **Fouisseur** : l'animal bénéficie d'un bonus de 10% quand il fait des jets d'*Atlétisme* pour creuser un trou.
- **Maître des crocs** : votre familier sait très bien utiliser ses crocs. Il augmente la valeur de *Combat au corps à corps* de 10% quand il attaque en utilisant ses crocs.
- **Maître des griffes** : votre familier sait très bien utiliser ses griffes ou ses serres. Il augmente la valeur de *Combat au corps à corps* de 10% quand il attaque en utilisant ses griffes ou ses serres.
