# Le combat

## Début du combat

L'ordre dans lequel les différents personnages vont jouer se détermine par rapport à leur vitesse. Le personnage à la vitesse la plus élevée commence puis les joueurs sont rangés en fonction de leur vitesse. Si deux personnages ont la même vitesse, l'ordre est déduit au hasard. 

## Faire des dégâts

Pour faire des dégâts, un personnage doit d'abord jeter un jet de combat (au corps à corps, à distance, via un sort, ...). Il réussi son action si le résultat du jet de dé est moins élevé que la valeur qu'il possède dans la compétence correspondante. Enfin, les dégâs qu'il inflige sont calculés selon la différence entre le résultat du dé et la valeur qu'il possède dans la compétence (en y ajoutant de potentiels bonus inhérents aux armes ou à des talents particulier).

### Embuscade

Le principe d'une embuscade est justement d'agir avant les autres. Durant une embuscade, les personnages vont jouer les premiers, selon l'ordre de leur vitesse, puis les joueurs ayant subi l'embuscade vont jouer. Au prochain tour, c'est la méthode de jeu de base qui prévaudra, soit la vitesse comme ordre de passage. 

